kaka_huet/config/routes.rb
Rails.application.routes.draw do
  resources :players
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "players#index"
end

kaka_huet/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.[](column)
    arel_table[column]
  end
end

module Arel
  module Predications
    alias_method :>, :gt
    alias_method :<, :lt
    alias_method :>=, :gteq
    alias_method :<=, :lteq
    alias_method :"!=", :not_eq
    alias_method :==, :eq
  end
end

kaka_huet/app/models/player.rb
class Player < ApplicationRecord
  has_secure_password

  validates_presence_of :name, :email
  validates_uniqueness_of :email, case_sensitive: false

  scope :enabled, -> { where enabled: true }
end

kaka_huet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

kaka_huet/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players
  def index
    @players = Player.all
  end

  # GET /players/1
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to @player, notice: "Player was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /players/1
  def update
    if @player.update(player_params)
      redirect_to @player, notice: "Player was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /players/1
  def destroy
    @player.destroy
    redirect_to players_url, notice: "Player was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:name, :email, :enabled, :password, :password_confirmation)
    end
end

kaka_huet/app/helpers/application_helper.rb
module ApplicationHelper
end

kaka_huet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>KakaHuet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mini.css/3.0.1/mini-default.min.css" integrity="sha512-fzA+tLgtwjys8FSpEdAGGamBJiWnHCwSkEu5P3EGr73U8AFnOSE1kzI6+RSYvf4zIs5BPWVrdzygD+nvZKbxIg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

kaka_huet/app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, required: true %>
  </div>

  <div>
    <%= form.label :enabled, style: "display: block" %>
    <%= form.check_box :enabled %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password, required: true %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

kaka_huet/app/views/players/_player.html.erb
<div id="<%= dom_id player %>">
  <p>
    <strong>Name:</strong>
    <%= player.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= player.email %>
  </p>

  <p>
    <strong>Enabled:</strong>
    <%= player.enabled %>
  </p>

</div>

kaka_huet/app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Show this player", @player %> |
  <%= link_to "Back to players", players_path %>
</div>

kaka_huet/app/views/players/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Players</h1>

<div id="players">
  <% @players.each do |player| %>
    <%= render player %>
    <p>
      <%= link_to "Show this player", player %>
    </p>
  <% end %>
</div>

<%= link_to "New player", new_player_path %>

kaka_huet/app/views/players/new.html.erb
<h1>New player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Back to players", players_path %>
</div>

kaka_huet/app/views/players/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @player %>

<div>
  <%= link_to "Edit this player", edit_player_path(@player) %> |
  <%= link_to "Back to players", players_path %>

  <%= button_to "Destroy this player", @player, method: :delete %>
</div>